Center issue
MicroFocus/alm-octane-csharp-rest-sdk pull request #35
Opened 2018-09-27 12:50 UTC by kdrtibor

New center link would cause the plugin to enter in a deadlock -> fix implies closing the httpwebrequest, otherwise .Net framework caches some data in the background and tries to reuse the last request to the same url, since that request was not disposed correctly it would hang the call -> entering in a deadlock

Defect id #694179:

2018-10-02 05:16 UTC, radislavB requested changes
We have now DisconnectAsync and Disconnect. I would expect that Disconnect is using DisconnectAsync  internally.
As well, implementation of DisconnectAsync  is not using try/catch on disconnection request. I would add it.

2018-10-03 07:06 UTC, slbruce commented
Is this ready to merge?

2018-10-03 07:36 UTC, vladbenchea commented
As long as it doesn't affect other projects, I think it's okay - @radislavB ?

2018-10-03 11:25 UTC, kdrtibor commented
I think we need the approval of @radislavB, from my point of view it is ok.

2018-10-04 15:16 UTC, merged